language: rust
cache: cargo

rust:
  - stable
env:
  global:
    - RUST_BACKTRACE=1
    # XXX: begin_test_transaction doesn't play nice over threaded tests
    - RUST_TEST_THREADS=1
    - SYNC_DATABASE_URL="mysql://travis@127.0.0.1/syncstorage"

services:
  - mysql

before_script:
  - rustup component add rustfmt-preview
  - mysql -e 'CREATE DATABASE IF NOT EXISTS syncstorage;'

script:
  - cargo fmt -- --check
  - cargo build
  - cargo test
  - ./scripts/build-docs.sh

notifications:
  email: false
  slack:
    secure: vT9sWtUuxk28g6xYKAsQmiPZllErOYVfx5lcL+/jo1eRFrmbpYnyndT6s+FxGI1547oizZ0IqZbHVvB7BUoSJixXJyQJYXW2MchwN1UeHrey8mYpF1GNEaJT7FMfqSkxUU9gvAZ3IU7zstNeTLbfG1GkLuzybp0WAiHl/ocUTz8=
