language: rust

rust:
    - stable

cache: cargo

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt -- --write-mode=diff
  # HACK: Force CI to fail if there are rustfmt diffs. We can stop doing this
  #       as soon as `cargo fmt -- --check` works in stable.
  - if [ "$(cargo fmt -- --write-mode=diff | wc -l)" != "0" ]; then exit 1; fi
  - cargo build
  - cargo test

notifications:
  email: false
  slack:
    secure: vT9sWtUuxk28g6xYKAsQmiPZllErOYVfx5lcL+/jo1eRFrmbpYnyndT6s+FxGI1547oizZ0IqZbHVvB7BUoSJixXJyQJYXW2MchwN1UeHrey8mYpF1GNEaJT7FMfqSkxUU9gvAZ3IU7zstNeTLbfG1GkLuzybp0WAiHl/ocUTz8=
