[package]
name = "syncstorage"
version = "0.1.5"
license = "MPL-2.0"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "Phil Jenvey <pjenvey@underboss.org>",
]
edition = "2018"

[profile.release]
# Enables line numbers in Sentry
debug = 1

[dependencies]
actix-web = "^1.0.7"
actix-rt = "0.2"
actix-cors = "0.1"
actix-http = "0.2"
actix-service = "0.4"
base64 = "0.10.1"
bytes = "0.4"
cadence = "0.18.0"
chrono = "0.4"
config = "0.9.3"
diesel = { version = "1.4.2", features = ["mysql", "r2d2"] }
diesel_logger = "0.1.0"
diesel_migrations = { version = "1.4.0", features = ["mysql"] }
docopt = "1.1.0"
env_logger = "0.6"
failure = "0.1.5"
futures = "0.1.28"
googleapis-raw = { version = "0", path = "../mozilla-rust-sdk/googleapis-raw" }
grpcio = { version = "0.5.0-alpha.1" }
lazy_static = "1.4.0"
hawk = "3.0.0"
hkdf = "0.8.0"
hmac = "0.7"
log = "0.4"
mime = "0.3"
mozsvc-common = "0.1"
num_cpus = "1.10"
protobuf = "2.7.0"
rand = "0.7"
regex = "1.3"
sentry = { version = "0.17.0", features = ["with_curl_transport"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
serde_urlencoded = "0.6.1"
sha2 = "0.8.0"
slog = { version = "2.5", features = ["max_level_trace", "release_max_level_info"] }
slog-async = "2.3"
slog-term = "2.4"
slog-mozlog-json = "0.1"
slog-scope = "4.1"
slog-stdlog = "4.0"
time = "0.1.42"
tokio-threadpool = "0.1.15"
url = "2.1.0"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
validator = "0.9"
validator_derive = "0.9"

[features]
db_test = []
