[package]
name = "syncstorage"
version = "0.1.0"
license = "MPL-2.0"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "Phil Jenvey <pjenvey@underboss.org>",
]

[dependencies]
actix = "0.7"
actix-web = "0.7.7"
base64 = "0.9.2"
cadence = "0.15.1"
chrono = "0.4"
config = "0.9.0"
diesel = { version = "1.3", features = ["mysql", "r2d2"] }
diesel_logger = "0.1.0"
diesel_migrations = { version = "1.3", features = ["mysql"] }
docopt = "1.0.0"
env_logger = "0.5.13"
failure = "0.1"
futures = "0.1"
lazy_static = "1.1.0"
hawk = "1.0.4"
hkdf = "0.6.0"
hmac = "0.6.3"
mozsvc-common = "0.1.0"
num = "0.2.0"
num_cpus = "1.8.0"
rand = "0.5.2"
regex = "1.0.5"
ring = "0.13.2"
serde = "1.0.67"
serde_derive = "1.0.67"
serde_json = "1.0.24"
sha2 = "0.7.1"
time = "0.1.40"
uuid = { version = "0.6.5", features = ["serde", "v4"] }
validator = "0.8.0"
validator_derive = "0.8.0"
