version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3306"
        environment:
            # MYSQL_RANDOM_ROOT_PASSWORD: yes
            MYSQL_ROOT_PASSWORD: random
            MYSQL_DATABASE: syncstorage
            MYSQL_USER: test
            MYSQL_PASSWORD: test

    syncstorage-rs:
        # build:
        #   context: .
        #   args: 
        #     HELPER_SCRIPT: 'purge_ttl'
        image: ${SYNCSTORAGE_RS_IMAGE:-syncstorage-rs:latest}
        restart: always
        ports:
          - "8000:8000"
        depends_on:
          - db
        environment:
          # RUST_BACKTRACE: full
          # RUST_LOG: debug
          SYNC_DATABASE_URL: mysql://root:random@db/syncstorage_rs
          SYNC_HOST: 0.0.0.0
          SYNC_MASTER_SECRET: INSERT_SECRET_KEY_HERE

volumes:
    db_data:

# Application runs off of port 8000.
# you can test if it's available with
# curl "http://localhost:8000/__heartbeat__"
