database_url = "mysql://sample_user:sample_password@localhost/syncstorage_rs"
master_secret = "some_secret_here"
# removing this line will default to moz_json formatted logs (which is preferred for production envs)
human_logs = 1 
