PORT=8000
RUST_BACKTRACE=1
RUST_LOG="debug"
SENTRY_DSN="see readme for instructions"
SYNC_DATABASE_URL="mysql://sample_user:sample_password@localhost/syncstorage_rs"
SYNC_MASTER_SECRET="your secret here"